### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by LeonardoGentile** [StevenTheEVILZ/gulp-syncronize#1]
Hello, thanks for this package.
Although it seems this is not working on my configuration.
This is what I'm using:

```
gulp.task('unused', function() {
    return syncronize({
        src:    'app/coffee/',   //Source folder
        target: 'app/js/',        //Output folder
        extensions: {
            'js': 'coffee', // /Corresponds .js files to the .coffee files; changes .js extension when checking
        }
    });
});
```
If I remove any file with `.coffee` extension from the `app/coffee` folder then the corresponding `.js` file into the `app/js/` folder is not removed.

**Comment by StevenTheEVILZ** [comment]
Fixed with 1.0.3. Please update!

Problem was with '/' at the end of src and target. Now that is supported but optional.

**Comment by LeonardoGentile** [comment]
Hi @StevenTheEVILZ, thanks very much for the quick fix, by the time I figured it out you had already fixed it!
Now I'm having another issue, I'm on node 0.10.36 and v0.12.7 (can't upgrade now) and to my surprise the string method `endsWith` is not defined! Can I help you by polyfilling this method in your script or using an alternative?

**Comment by LeonardoGentile** [comment]
Maybe adding this to the requirements? https://www.npmjs.com/package/string.prototype.endswith
